# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: obstacle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='obstacle.proto',
  package='org.copdai',
  serialized_pb=_b('\n\x0eobstacle.proto\x12\norg.copdai\"\x91\x01\n\x0e\x43\x61meraObstacle\x12\x0c\n\x04xmin\x18\x01 \x02(\x01\x12\x0c\n\x04ymin\x18\x02 \x02(\x01\x12\x0c\n\x04xmax\x18\x03 \x02(\x01\x12\x0c\n\x04ymax\x18\x04 \x02(\x01\x12\r\n\x05\x64\x65pth\x18\x05 \x02(\x01\x12\x12\n\nconfidence\x18\x06 \x02(\x01\x12\x16\n\x0e\x63lassification\x18\x07 \x01(\t\x12\x0c\n\x04time\x18\x08 \x02(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CAMERAOBSTACLE = _descriptor.Descriptor(
  name='CameraObstacle',
  full_name='org.copdai.CameraObstacle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xmin', full_name='org.copdai.CameraObstacle.xmin', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ymin', full_name='org.copdai.CameraObstacle.ymin', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xmax', full_name='org.copdai.CameraObstacle.xmax', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ymax', full_name='org.copdai.CameraObstacle.ymax', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='depth', full_name='org.copdai.CameraObstacle.depth', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='org.copdai.CameraObstacle.confidence', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='classification', full_name='org.copdai.CameraObstacle.classification', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='org.copdai.CameraObstacle.time', index=7,
      number=8, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['CameraObstacle'] = _CAMERAOBSTACLE

CameraObstacle = _reflection.GeneratedProtocolMessageType('CameraObstacle', (_message.Message,), dict(
  DESCRIPTOR = _CAMERAOBSTACLE,
  __module__ = 'obstacle_pb2'
  # @@protoc_insertion_point(class_scope:org.copdai.CameraObstacle)
  ))
_sym_db.RegisterMessage(CameraObstacle)


# @@protoc_insertion_point(module_scope)
